### ISSUE TITLE
Is this an extension for inkscape?

### ISSUE THREAD

**Issue by world33** [james-bird/layer-to-svg#1]
Hi,

Is this an extension for inkscape? I tried to install in the extensions directory but it did not show up in the extensions menu.

Thanks

**Comment by james-bird** [comment]
Hi,
No, it isn't an extension. It is just a little script I wrote to split-up Inkscape files into layers. You save your standard Inkscape .svg file, then run the python script on it and it will generate the new files in the same directory.
